questions/config/routes.rb
Rails.application.routes.draw do
    resources :users 
    resources :posts do
      resources :comments
    end
    root 'posts#index'
    resource :session, only: [:new, :create, :destroy]
    resources :search, only: [:index]
    
    namespace :api do
      namespace :v1 do
        resources :users
        resources :posts do
          resources :comments, only: [:create, :new]
        end
        root 'posts#index'
        resource :session, only: :create
      end
    end    
  end

questions/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  paginates_per 5
  
end

questions/app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::BaseController
  skip_before_action :verify_authenticity_token, only: :create

  def new
    render json: {error: "You don't have permission to access these resources"}, status: :unauthorized
    if !(current_user)
    @post = Post.find(params["post_id"])
    @comment = Comment.new

  end
  

  def create
    @post = Post.find(params["post_id"])
    
    user_id = comment_params["comment"]["user_id"]
    reply = comment_params["comment"]["reply"]
    
    @comment = Comment.new(post_id: @post.id, user_id: user_id, body: reply )

    if @comment.save
      render json @comment
    else
      
        render json: @comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.permit(:post_id, comment: [:user_id, :reply] )
  end

end

questions/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  
  def new
    redirect_to post_path, notice: 'You must be logged in to comment' if !(current_user)
    @post = Post.find(params["post_id"])
    @comment = Comment.new

  end

  def edit
    @post = Post.find(params["post_id"])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params["post_id"])
    @comment= Comment.find(params[:id])
    @comment.post_id = params[:post_id]
    if @comment.user_id === current_user.id
      @comment.update(comment_params2)
      redirect_to post_path(@post), notice: 'Comment edited!'
    end
  end

  

  def create
    @post = Post.find(params["post_id"])
    
    user_id = comment_params["comment"]["user_id"]
    reply = comment_params["comment"]["reply"]
    
    @comment = Comment.new(post_id: @post.id, user_id: user_id, body: reply )

    if @comment.save
      redirect_to post_path(@post), method: :patch, notice: 'Reply successfully created.'
    else
      
      render :new
    end
  end

  def destroy
    @post = Post.find(params["post_id"])
    @comment = Comment.find(params[:id])
    if @comment.user_id === current_user.id
      @comment.destroy
    redirect_to post_path(@post), notice: 'Comment deleted!' 
    else flash[:notice] = "Must be your question to delete"
    end
  end

  private

  def comment_params
    params.permit(:post_id, comment: [:user_id, :reply] )
  end

  def comment_params2
    params.permit(:post_id, :user_id, :body)
    
  end


end

questions/app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

questions/app/views/comments/edit.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="localhost:3000">QuestionBox</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="localhost:3000">Home</a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if !current_user %>
      <li><%= link_to "Login", new_session_path %> </li>
      <li><%= link_to "Register Account", new_user_path %></li>
      <% else %>
      <li><%= link_to "Log Out", session_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
</nav>

<h1 class='col-md-6 offset-md-3 pb-3'>Edit Your Reply</h1>

<div class='form-signin col-md-6 offset-md-3'>
        <%= form_with url: post_comment_path(@post, @comment), method: :patch, local:true do |form| %>
           
           <div class="form-group"> 
            <%= form.label :body %>
            <%= form.text_area :body, :class => "form-control-lg" %>
            </div>
            <div class="form-group">
            <%= form.hidden_field :user_id, :value =>current_user.id %>
            <%= form.hidden_field :post_id, :value => @post.id %>
            </div>
            
            <%= form.submit %>
        <% end %>
</div>
<div>
<%= link_to 'Go Back', post_path(id:@post.id), method: :get %>

questions/app/views/comments/new.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="localhost:3000">QuestionBox</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="localhost:3000">Home</a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if !current_user %>
      <li><%= link_to "Login", new_session_path %> </li>
      <li><%= link_to "Register Account", new_user_path %></li>
      <li><%= link_to 'Go Back', post_path(id:@post.id), method: :get %></li>
      <% else %>
      <li><%= link_to "Log Out", session_path, method: :delete %></li>
      <li><%= link_to 'Go Back', post_path(id:@post.id), method: :get %></li>
      <% end %>
    </ul>
  </div>
</nav>

<h1 class='col-md-6 offset-md-3 pb-3'>Create a Reply</h1>

<div class='form-signin col-md-6 offset-md-3'>
        <%= form_with url: post_comments_path, scope: "comment", local:true do |form| %>
           
           <div class="form-group"> 
            <%= form.label :reply %>
            <%= form.text_area :reply, :class => "form-control-lg" %>
            </div>
            <div class="form-group">
            <%= form.hidden_field :user_id, :value =>current_user.id %>
            <%= form.hidden_field :post_id, :value => @post.id %>
            </div>
            
            <%= form.submit %>
        <% end %>
</div>
<div>