questions/config/routes.rb
Rails.application.routes.draw do
    resources :users 
    resources :posts do
      resources :comments
    end
    root 'posts#index'
    resource :session, only: [:new, :create, :destroy]
    resources :search, only: [:index]
    
    namespace :api do
      namespace :v1 do
        resources :users
        resources :posts do
          resources :comments, only: [:create, :new]
        end
        root 'posts#index'
        resource :session, only: :create
      end
    end    
  end

questions/app/models/user.rb
class User < ApplicationRecord
    has_secure_token :api_token
    has_secure_password
    validates :username, uniqueness: true
    validates :password, presence: true, length: {minimum: 5}, allow_nil: true
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_one_attached :photo

    

    def self.send_weekly_email
        posts = Post.where("created_at::date <= ?", Date.today - 7.to_i).select(:body, :question)
            if posts.count > 1
                User.select(:id, :email).find_each do |u|
                    UserMailer.delay.send_weekly_email(u.email, posts)
                end
            end
    end

    private
    
    def params
        params.permit(:body, :question)
    end

end

questions/app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
    

    skip_before_action :verify_authentication, only: [:index, :new, :create, :show]
    protect_from_forgery with: :null_session
    def index
        @users = User.all
        render json: @users
    end

    def create
        
        @user = User.new(user_params)

        if @user.save
            render json: @user, status: :created
        else
            render json: @user.errors, status: :unprocessable_entity
        end
    end
    
    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
        @posts = @user.posts
        render json: @posts
    end

    def destroy
        if  @user.destroy
            render json: @user, status: :accepted
        else
            render json: @user.errors, status: :unauthorized
        end
    end

    private
    def user_params
        params.permit(:username, :password)
    end
end

questions/app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :verify_authentication, only: [:new, :create, :index, :show]

    
    def create 
        @user = User.new(user1_params)
    
            if @user.save
                UserMailer.with(user: @user).welcome_email.deliver_now
                session[:user_id] = @user.id
                redirect_to root_path, notice: "User successfully created."
            else
                redirect_to new_user_path, notice: "Something went wrong, please try again."
            end
    end

    def index
    end

    def edit
        set_user
    end

    def update
        set_user
        if current_user.id != @user_id
            flash[:notice] = "You cannot update this user"
        end
        if @user.update_attributes(user_params)
            flash[:notice] = "Profile updated"
            redirect_to @user
        else
            flash[:notice] = "Unsuccesful"
            redirect_to @user
        end
       
    end

    def new
        @user = User.new
    end

    def show
        set_user
        @posts = @user.posts
    end

    def destroy
        set_user
        if current_user == @user
            @user.destroy
            redirect_to root_path
        else
            flash[:notice] = "Could not delete"
            redirect_to @user
        end
    end

    private
        def user_params
            params.require(:user).permit(:username, :password, :photo, :email)
        end
        def user1_params
            params.permit(:username, :password, :photo, :email)
        end
        def set_user
            @user = User.find(params[:id])
        end
        
end

questions/app/helpers/api/users_helper.rb
module Api::UsersHelper
end

questions/app/views/users/edit.html.erb
<nav class="navbar navbar-inverse jumbotron">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class ="display-1"><%= link_to 'QuestionBox', posts_path, class: "questionbox" %>
      </div>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if !current_user %>
      <li class="pb-2"><%= link_to "Login", new_session_path %> </li>
      <li class="pb-2"><%= link_to "Register Account", new_user_path %></li>
      <li class="pb-2"><%= link_to 'Back', root_path %></li>
      <% else %>
      <li class="pb-2"><%= link_to 'Back', root_path %></li>
      <li class="pb-2"><%= link_to "Log Out", session_path, method: :delete %></li>
      <li class="pb-2"><%= link_to 'Delete Account', user_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
</nav>

<h1 class='h3 mt-5 mb-3 font-weight-normal text-center'>Edit Your Profile: <%= @user.username.capitalize %> <br>
User Email: <%= @user.email %> </h1>


<%= form_with model: @user, method: :patch, local: true,  :html => {:class => 'form-signin col-md-6 offset-md-3'} do |form| %>
  

  <div class="form-group">
    <%= form.label :username %>
    <%= form.text_field :username, :class => "form-control", :placeholder => 'edit username' %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, :class => "form-control", :placeholder => 'edit email' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control', :placeholder => 'edit password' %>
  </div>

  <div class="form-group">  
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>


  <%= form.submit "Edit my Account", :class => "btn btn-lg btn-info btn-block" %>
  
<% end %>

questions/app/views/users/new.html.erb
<nav class="navbar navbar-inverse jumbotron">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class ="display-1"><%= link_to 'QuestionBox', posts_path,class: "questionbox" %>
      </div>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if !current_user %>
      <li><%= link_to "Login", new_session_path %> </li>
      <% end %>
    </ul>
  </div>
</nav>

<h1 class='h3 mt-5 mb-3 font-weight-normal text-center'>Sign Up</h1>


<%= form_with url: users_path, local: true,  :html => {:class => 'form-signin col-md-6 offset-md-3'} do |form| %>
  

  <div class="form-group">
    <%= form.label :username %>
    <%= form.text_field :username, :class => "form-control", :placeholder => 'username' %>
    </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, :class => "form-control", :placeholder => 'email' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control', :placeholder => 'password' %>
  </div>


  <%= form.submit "Create my Account", :class => "btn btn-lg btn-info btn-block" %>
  
<% end %>

questions/app/views/users/show.html.erb
<nav class="navbar navbar-inverse jumbotron">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class ="display-1"><%= link_to 'QuestionBox', posts_path, class: "questionbox" %>
      </div>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if !current_user %>
      <li class="pb-2"><%= link_to "Login", new_session_path %> </li>
      <li class="pb-2"><%= link_to "Register Account", new_user_path %></li>
      <li class="pb-2"><%= link_to 'Back', root_path %></li>
      <% else %>
      <li class="pb-2"><%= link_to 'Back', root_path %></li>
      <li class="pb-2"><%= link_to 'Edit Profile', edit_user_path(@user) %></li>
      <li class="pb-2"><%= link_to "Log Out", session_path, method: :delete %></li>
      <li class="pb-2"><%= link_to 'Delete Account', user_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
</nav>

<p class='h3 mt-5 mb-3 font-weight-normal text-center'>Profile Page For: <%= @user.username.capitalize %> <br>
<br>
User Email: <%= @user.email %> </p>
<p class='h4 mt-5 mb-3 font-weight-normal text-center'> Number of Posts: <%= @posts.count %> </p>

<% if notice %>
<p><%= notice %></p>
<% end %>


  <% if @user.photo.attached? %>
    
      <div class="text-center mb-2">
        <strong> Profile Photo </strong>
      </div>
    <div class = "container">
      <div class="row justify-content-center"> 
        <%= image_tag @user.photo, style: "max-width:150px; max-height: 225px;" %>
      </div>
    </div>
  <% end %>

<div>
<% @posts.each do |post| %>
    <div class="card border-secondary text-center" style="width: 30rem;">
        <div class="card-body">
          <h3 class="card-title">
          <%= post.question %>
          </h3>
        </div>
          <p class="card-text">
          <%= post.body %>
          </p>
          <p class="card-text">
          <%= link_to 'Show', post_path(post) %>
          </p>
  <% end %>
      
</div>