questions/config/routes.rb
Rails.application.routes.draw do
    resources :users 
    resources :posts do
      resources :comments
    end
    root 'posts#index'
    resource :session, only: [:new, :create, :destroy]
    resources :search, only: [:index]
    
    namespace :api do
      namespace :v1 do
        resources :users
        resources :posts do
          resources :comments, only: [:create, :new]
        end
        root 'posts#index'
        resource :session, only: :create
      end
    end    
  end

questions/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :body, presence: true
    paginates_per 10
    include PgSearch
    
    pg_search_scope :search_post, against: [:body]
    pg_search_scope :search_all_variants,
        against: [:body, :user_id],
        using: {
            tsearch: { dictionary: 'english' }
        }
    
    pg_search_scope :search_all_partial_matches,
        against: [:body, :user_id],
        using: {
            tsearch: { prefix: true }
    }    

    
end

questions/app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::BaseController
    before_action :set_post, only: [:destroy]
    skip_before_action :verify_authentication, only: [:index, :show]
    skip_before_action :verify_authenticity_token, only: :create
    
    def index
      @posts=Post.all
      render json: @posts, status: :accepted
    end
  
    def new
      @post=Post.new
    end

    def update
      @post = Post.find(params[:id])
      if  @post.update(post_params)
          render json: @post, status: :accepted
      else
          render json: @post.errors.messages, status: :unprocessable_entity
      end
    end
  
    def create
      @post = Post.new(post_params)
      
      if @post.save
        render json: @post, status: :created
      else
        render json: @post.errors, status: :unprocessable_entity
      end
    end
  
    def show
      @post = Post.find(params[:id])
      render json: @post
    end
  
    def destroy
        @post = Post.find(params[:id])
        if  @post.destroy 
            render json: @post, status: :accepted
        else 
            render json: @post.errors.messages, status: :unauthorized
        end
    end
  
    private
    def post_params
      params.require(:post).permit(:question, :body, :user_id)
    end
  
    def set_post
      @post = Post.find(params["post_id"] || params["id"])
    end


end

questions/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  skip_before_action :verify_authentication
  
  def index
    @posts=Post.page(params[:page])
  end

  def new
    redirect_to root_path, flash[:notice] = 'You must be logged in to post a question!' if !(current_user)
    @post=Post.new
  end

  def create
    @post = Post.new(post_params)
    
    if @post.save
      redirect_to posts_path (@post)
    else
      render :new 
    end
  end

  def edit
    @comments = @post.comments
  end

  def update
    @comments = @post.comments
    if @post.comments.count === 0 && @post.user_id === current_user.id
      @post.update(post_params2)
      redirect_to post_path(@post)
    else
      redirect_to post_path(@post)
      flash[:notice] = "Something went wrong!"
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def destroy
    if @post.user_id == current_user.id
      @post.destroy
      redirect_to root_path
    else
      redirect_to root_path
      flash[:notice] = "Must be your question to delete"
    end
    
  end

  private
  def post_params
    params.require(:post).permit(:question, :body, :user_id)
  end

  def post_params2
    params.permit(:question, :body, :user_id)
  end

  def set_post
    @post = Post.find(params["post_id"] || params["id"])
  end


end

questions/app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

questions/app/views/posts/edit.html.erb
<nav class="navbar navbar-inverse jumbotron">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class ="display-1"><%= link_to 'QuestionBox', posts_path, class: "questionbox" %>
      </div>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if !current_user %>
      <li class="pb-2"><%= link_to "Login", new_session_path %> </li>
      <li class="pb-2"><%= link_to "Register Account", new_user_path %></li>
      <% else %>
      <li class="pb-2"><%=link_to current_user.username, user_path(id:current_user.id)  %></li>
      <li class="pb-2"><%= link_to "Log Out", session_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
</nav>


<div class='form-signin col-md-6 offset-md-3'>
        <%= form_with url: post_path(@post), method: :patch, local:true do |form| %>
           <div class="form-group"> 
                <%= form.label :question %>
                <%= form.text_field :question, :class => "form-control" %>
            </div>
            <div class="form-group"> 
                <%= form.label :body %>
                <%= form.text_area :body, :class => "form-control" %>
            </div>
            <div class="form-group">
                <%= form.hidden_field :user_id, :value =>current_user.id %>
            </div>
            
            <%= form.submit %>
        <% end %>
    </div>
<div>
<%= link_to 'Go Back', post_path(id:@post.id), method: :get %>

questions/app/views/posts/index.html.erb
<nav class="navbar navbar-inverse jumbotron" style="background-color: #F4F7F5;>
  <div class="container-fluid">
    <div class="navbar-header">
      <div class ="display-1"><%= link_to 'QuestionBox', posts_path, class: "questionbox" %>
      </div>
    </div>

    <ul class="nav navbar-nav navbar-right p-3">
      <% if !current_user %>
        <li class="pb-2"><%= link_to "Login", new_session_path %> </li>
        <li class="pb-2"><%= link_to "Register Account", new_user_path %></li>
        <li class="pb-2"><%= link_to 'Search Posts', search_index_path %></li>
      <% else %>
        <li class="pb-2"><%=link_to current_user.username.capitalize, user_path(id:current_user.id)  %></li>
        <li class="pb-2"><%= link_to "Log Out", session_path, method: :delete %></li>
        <li class="pb-2"><%= link_to 'Search Posts', search_index_path %></li>
        <li class="pb=2"><% if current_user %> 
                        <%= link_to 'Post a Question', new_post_path %>	
                      <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
<div>
<%= paginate @posts %> 
<%= page_entries_info @posts %>
</div>
<div>
<% if notice %>
  <p class="alert alert-info mt-4" role="alert"><%= notice %></p>
<% end %>
</div>

<div class = "createspace">
  <% @posts.each do |post| %>
    <div class = "loop">
      <h3 class = "questindex">
        <%= link_to post.question, post_path(post) %>
      </h3> 
      <div class="questbody">  
          <%= Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(post.body).html_safe %>
        <p class = "postfooters">  
          Posted By: <%= link_to User.find(post.user_id).username.capitalize, user_path(id: post.user_id), class: "indexlink"  %>
          <br>
          Posted On: <%= post.created_at.strftime("%B %d %Y, %l:%M%P") %>
          <br>
          Number of comments: <%= link_to post.comments.count, post_path(post), class: "indexlink"%>
          <br>
        </p>  
      </div>
    </div>
    <br>
    <br>      
  <% end %>
</div>

questions/app/views/posts/new.html.erb
<nav class="navbar navbar-inverse jumbotron">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class ="display-1"><%= link_to 'QuestionBox', posts_path, class: "questionbox" %>
      </div>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if !current_user %>
      <li class="pb-2"><%= link_to "Login", new_session_path %> </li>
      <li class="pb-2"><%= link_to "Register Account", new_user_path %></li>
      <% else %>
      <li class="pb-2"><%=link_to current_user.username, user_path(id:current_user.id)  %></li>
      <li class="pb-2"><%= link_to "Log Out", session_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
</nav>

<h1>Create New Post</h1>
<div>
    <div class='form-signin col-md-6 offset-md-3'>
        <%= form_with url: posts_path, scope: "post", local:true do |form| %>
           <div class="form-group"> 
            <%= form.label :question %>
            <%= form.text_field :question, :class => "form-control" %>
            </div>
           <div class="form-group"> 
            <%= form.label :body %>
            <%= form.text_area :body, :class => "form-control" %>
            </div>
            <div class="form-group">
            <%= form.hidden_field :user_id, :value =>current_user.id %>
            </div>
            
            <%= form.submit %>
        <% end %>
    </div>
</div>

questions/app/views/posts/show.html.erb
<nav class="navbar navbar-inverse jumbotron">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class ="display-1"><%= link_to 'QuestionBox', posts_path, class: "questionbox" %>
      </div>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if !current_user %>
      <li class="pb-2"><%= link_to "Login", new_session_path %> </li>
      <li class="pb-2"><%= link_to "Register Account", new_user_path %></li>
      <% else %>
      <li class="pb-2"><%=link_to current_user.username.capitalize, user_path(id:current_user.id)  %></li>
      <li class="pb-2"><%= link_to "Log Out", session_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
</nav>
<div>
<% if notice %>
  <p class="alert alert-info mt-4" role="alert"><%= notice %></p>
<% end %>
</div>

<h1 class="text-center pb-5 mb-5">Post Details</h1>
<div class = "row">
  <div class="col-md-6 offset-md-3">
      <strong>Question:</strong>
  </div>
  <div class="col-md-6 offset-md-3">
    <%= @post.question %>
  </div>
  <br>
  <br>
  <div class="col-md-6 offset-md-3">
  <strong>Body:</strong>
  </div>
  <div class="col-md-6 offset-md-3">
  <%= Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(@post.body).html_safe %>
  </div>
  <div class="col-md-6 offset-md-3">
  <strong>Username:</strong>
  </div> 
  <div class = "col-md-6 offset-md-3">
  <%= link_to User.find(@post.user_id).username.capitalize, user_path(id: @post.user_id) %>
  </div>
</div>
  <div class = "text-center pb-2">
    <% if @post.comments.count === 0 && User.find(@post.user_id) === current_user %>
      <button type="button" class="btn btn-light mr-2">
        <%= link_to 'Edit', edit_post_path(@post) %>
      </button>
    <% end %>
    <% if current_user == User.find(@post.user_id) %>
      <button type="button" class="btn btn-light mr-2">
        <%= link_to 'Destroy', post_path(@post), method: :delete %>
      </button>
    <% end %>
    <% if current_user %>
     <button type="button" class="btn btn-light">
    <%= link_to 'Comment', new_post_comment_path(post_id:@post.id) %>	
     </button>
    <% end %>
  </div>
<br>

<h3 class = "text-center pt-3 mt-3">
Replies
</h3>
<div class = "col-md-6 offset-md-3">
    <% @comments.each do |comment| %>
      <strong>Comment:</strong>  
        <%= (comment.body) %>
        <br>
        <br>
      <strong>By User:</strong> 
        <%= link_to User.find(comment.user_id).username.capitalize, user_path(id: comment.user_id) %>
        <br>
      <p class = "pt-2 pb-3">
        <% if comment.user_id === current_user.id %>
          <button type="button" class="btn btn-light">
            <%= link_to 'Delete', post_comment_path(@post, comment), local: true, method: :delete %>
          </button>
          <button type="button" class="btn btn-light">
            <%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
          </button>
        <% end %> 
      </p>
    <% end %>
  
</div>